name: lint

on:
  - push
  - pull_request

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - uses: dschep/install-poetry-action@v1.3
      - name: Install dependencies
        run: poetry install
      - run: black --check --diff .
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - uses: dschep/install-poetry-action@v1.3
      - name: Install dependencies
        run: poetry install
      - run: pylint --errors-only profile_stack tests
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: 'Dockerfile'
      - name: dev.Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: 'dev.Dockerfile'
      - name: platform.Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: 'platform.Dockerfile'
